import os
import re

from dotenv import load_dotenv
from google import genai
from google.genai import types
import json

load_dotenv()

import config


class GeminiService:
    """
    Service responsible for communicating with the Google Gemini API.

    Falls back to a lightweight local summarizer when no GEMINI_API_KEY is configured,
    allowing end-to-end tests to run locally without external API access.
    """

    def __init__(self):
        api_key = config.GEMINI_API_KEY

        if api_key:
            self.client = genai.Client(api_key=api_key)
            self._use_mock = False
        else:
            self.client = None
            self._use_mock = True

    def generate(self, prompt: str) -> str:
        """
        Generate a response from Gemini or a local fallback.
        """
        if self._use_mock:
            # Extract only the source text from between the delimiters
            # that PromptEngine always wraps it in:
            #   Source Text:\n--------------------\n<text>\n--------------------
            match = re.search(
                r'Source Text:\s*-{10,}\s*(.*?)\s*-{10,}',
                prompt,
                re.DOTALL,
            )
            if match:
                source = match.group(1).strip()
            else:
                # Fallback: use the last non-empty block of the prompt
                # (avoids returning instruction lines)
                blocks = [b.strip() for b in prompt.split('\n\n') if b.strip()]
                source = blocks[-1] if blocks else prompt.strip()

            sentences = re.split(r'(?<=[.!?])\s+', source)
            if len(sentences) <= 3:
                return ' '.join(sentences).strip()
            return ' '.join(sentences[:3]).strip()

        try:
            response = self.client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt,
            )
            return response.text.strip()

        except Exception as e:
            raise RuntimeError(f"Gemini API Error: {str(e)}")
        
    def generate_code_review(self, batch, local_report, dependency_graph):
        """
        Generic Gemini generation.
        Used by Code Reviewer, SQL Generator,
        Regex Generator, Unit Test Generator, etc.
        """
        if self._use_mock:
          return {
              "model": "mock",
              "batch_files": batch["files"],
              "review": {}
          }
        def _filter_local_report(self, local_report, batch_files):

          filtered = {}

          batch_files = set(batch_files)

          for key, value in local_report.items():

              if isinstance(value, list):

                  filtered[key] = []

                  for item in value:

                      files = {
                          item.get("file"),
                          item.get("file1"),
                          item.get("file2"),
                          item.get("filename"),
                      }

                      files.discard(None)

                      if files & batch_files:
                          filtered[key].append(item)

              elif isinstance(value, dict):

                  filename = value.get("filename")

                  if filename is None or filename in batch_files:
                      filtered[key] = value

              else:
                  filtered[key] = value

          return filtered
        
        filtered_local_report = self._filter_local_report(
            local_report,
            batch["files"]
        )

        filtered_dependency_graph = {
            file: dependency_graph.get(file, [])
            for file in batch["files"]
        }
        
        system_prompt = """
        You are an expert Senior Software Engineer, Software Architect, Security Engineer, Performance Engineer, and Code Reviewer.

      You are reviewing a software project.

      You are provided with:

      1. Source code files.
      2. A local static analysis report generated by our code analyzer.

      The local analyzer has ALREADY completed:

      - Syntax Validation
      - File Statistics
      - Security Pattern Scan
      - Duplicate Code Detection
      - Complexity Analysis
      - Dependency Analysis
      - Project Structure Analysis

      Treat the local analysis as the source of truth.

      --------------------------------------------------------
      IMPORTANT INSTRUCTIONS
      --------------------------------------------------------

      DO NOT repeat:

      - Syntax validation
      - Security pattern scanning
      - Duplicate detection
      - Complexity calculations
      - Dependency analysis
      - File statistics
      - Project structure analysis

      Do NOT waste tokens explaining results that already exist inside the local report.

      Instead, use those reports as context for your reasoning.

      If the local analyzer reports an issue, explain WHY it matters and HOW it can be improved instead of detecting it again.

      If no issue exists in the local report, do not invent one.

      --------------------------------------------------------
      YOUR TASK
      --------------------------------------------------------

      Review the code from an experienced software engineer's perspective.

      Focus only on things requiring reasoning and experience.

      Perform the following analyses:

      --------------------------------------------------------
      1. Code Summary
      --------------------------------------------------------

      Explain:

      - Purpose of the project
      - Architecture
      - Main modules
      - Flow of execution
      - Responsibilities of important files

      --------------------------------------------------------
      2. Logic Bug Detection
      --------------------------------------------------------

      Find:

      - Logical mistakes
      - Incorrect algorithms
      - Incorrect assumptions
      - Missing edge cases
      - Race conditions
      - Incorrect API usage
      - Invalid business logic

      Do NOT report syntax errors.

      --------------------------------------------------------
      3. Performance Review
      --------------------------------------------------------

      Identify:

      - Inefficient algorithms
      - Poor data structures
      - Nested loops
      - Repeated computations
      - Unnecessary allocations
      - Memory inefficiencies
      - Database inefficiencies
      - Network inefficiencies

      Explain WHY.

        --------------------------------------------------------
        4. Code Readability
        --------------------------------------------------------

        Evaluate:

        - Code organization
        - Function readability
        - Variable naming
        - Control flow
        - Maintainability
        - Large methods
        - Deep nesting

        --------------------------------------------------------
        5. Best Practices
        --------------------------------------------------------

        Review adherence to:

        - SOLID
        - DRY
        - KISS
        - Separation of Concerns
        - Clean Architecture
        - Language-specific conventions

        --------------------------------------------------------
        6. Refactoring Suggestions
        --------------------------------------------------------

        Suggest improvements like:

        - Extract Method
        - Split Large Class
        - Remove Duplicate Logic
        - Better Design Patterns
        - Dependency Injection
        - Modularization

        Explain benefits.

        --------------------------------------------------------
        7. Production Readiness
        --------------------------------------------------------

        Evaluate:

        - Error handling
        - Validation
        - Logging
        - Scalability
        - Maintainability
        - Reliability
        - Security architecture
        - Testability

        Provide an overall production readiness score (0-100).

        --------------------------------------------------------
        8. Documentation
        --------------------------------------------------------

        Generate concise documentation for:

        - Modules
        - Classes
        - Important functions

        --------------------------------------------------------
        9. Unit Testing Suggestions
        --------------------------------------------------------

        Suggest important test cases.

        For each test include:

        - Test Name
        - Purpose
        - Expected Behaviour

        Do NOT generate complete test code.

        --------------------------------------------------------
        10. Improved Code
        --------------------------------------------------------

        Only if necessary.

        Rewrite ONLY functions/classes that significantly benefit from improvement.

        Do NOT rewrite the entire project.

        Explain why each improvement was made.

        --------------------------------------------------------
        OUTPUT FORMAT
        --------------------------------------------------------

        Return ONLY valid JSON.

        Do not include markdown.

        Do not include explanations outside JSON.

        Use exactly this schema:

        {
          "summary": {
            "overview": "",
            "architecture": "",
            "modules": []
          },

          "logic_bugs": [
            {
              "severity": "",
              "title": "",
              "description": "",
              "recommendation": ""
            }
          ],

          "performance": [
            {
              "severity": "",
              "issue": "",
              "reason": "",
              "recommendation": ""
            }
          ],

          "readability": [
            {
              "severity": "",
              "issue": "",
              "recommendation": ""
            }
          ],

          "best_practices": [
            {
              "severity": "",
              "issue": "",
              "recommendation": ""
            }
          ],

          "refactoring": [
            {
              "title": "",
              "reason": "",
              "recommendation": ""
            }
          ],

          "production_readiness": {
            "score": 0,
            "summary": "",
            "strengths": [],
            "weaknesses": [],
            "missing": []
          },

          "documentation": {
            "overview": "",
            "classes": [],
            "functions": []
          },

          "unit_tests": [
            {
              "name": "",
              "purpose": "",
              "expected": ""
            }
          ],

          "improved_code": [
            {
              "file": "",
              "function": "",
              "reason": "",
              "code": ""
            }
          ]
        }
        """

        '''
        Here We will not send full project or full source code to AI, as it will massively
        increase the API cost. What we will do is first we will filter the important files
        from the project based on the score calculated. The score is calculated based on
        various factors like dependency grpah, functions, etc.
        Then from the filtered_files Eg: [main.py, api.py, auth.py]
        We will modified the code to functions and classes. That means each file is 
        combination of functions and classes
        Eg auth.py -> login() + create_token()
        It will remove uncessary lines 
        Then we will not send every files to AI, we will create batches from filtered files
        Each batch will consist of 2-3 files(for eg)
        
        Gemini will recieve only system prompt, current batch[from batches], filtered 
        local report and dependecy graph, instead of whole project. It will reduce API
        cost massively
        
        Then we will merge the response of all batches into one response and return it to 
        frontend....
        '''
        prompt = f"""
          Files in Current Batch:
          {json.dumps(batch["files"], ensure_ascii=False)}

          Code Chunks:
          {json.dumps(batch["chunks"], ensure_ascii=False)}

          Dependency Graph:
          {json.dumps(filtered_dependency_graph, ensure_ascii=False)}

          Local Analysis Report:
          {json.dumps(filtered_local_report, ensure_ascii=False)}

          Generate the review using ONLY the supplied code chunks.

          Use the dependency graph to understand relationships between files.

          Use the local analysis as context only.

          Do not repeat the local analysis.

          Return ONLY valid JSON.
                """
        
        try:
            response = self.client.models.generate_content(
                model="gemini-2.5-flash",
                contents=[system_prompt, prompt],
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    temperature=0.2,
                    max_output_tokens=16384
                )
            )
            text = response.text.strip()

            if text.startswith("```"):
                text = (
                    text.replace("```json", "")
                        .replace("```", "")
                        .strip()
                )

            try:
                review = json.loads(text)
            except json.JSONDecodeError as e:
                raise RuntimeError(
                    f"Gemini returned invalid JSON:\n{text}"
                ) from e

            return {
                "model": config.GEMINI_MODEL,
                "batch_files": batch["files"],
                "review": review,
            }

        except Exception as e:
            raise RuntimeError(f"Gemini api error: {e}")