FROM python:3.12.0

WORKDIR /app

COPY requirements-backend.txt .

RUN apt-get update \
    && apt-get install -y --no-install-recommends poppler-utils \
    && rm -rf /var/lib/apt/lists/* \
    && python -m pip install --no-cache-dir -r requirements1-backend.txt \
    && python -m spacy download en_core_web_sm

COPY . .

EXPOSE 8001

CMD ["uvicorn", "main:fast_app", "--host", "0.0.0.0"]